- hosts: 172.31.86.146
  become: True
  tasks:
   - name: Install apache server
     yum: 
      name: httpd
      state: present
   - name: start & enable
     service: 
      name: httpd
      state: started
      enable: True   
      